---
abstract: 'Convert between Ethiopic wordspaces and ASCII spaces.'
author:
  - 'Daniel Yacob <dyacob\@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Convert-Wordspace
provides:
  Convert::Number::Digits:
    file: lib/Text/Convert/Wordspace.pm
    version: '0.01'
requires:
  perl: v5.6.1
resources:
  bugtracker: https://github.com/dyacob/Text-Convert-Wordspace/issues
  homepage: https://github.com/dyacob/Text-Convert-Wordspace
  license: http://dev.perl.org/licenses/
  repository: https://github.com/dyacob/Text-Convert-Wordspace.git
version: '0'
x_authority: cpan:dyacob
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
